### ISSUE TITLE
[Bug] Deleting in symmetry mode can leave ghost blocks [20w19a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1958]
### Short Description of the issue:
Sometimes when deleting something in symmetry mode, it looks like one side's copy hasn't been deleted. This block cannot be interacted with because it's not actually there. Placing another thing on the ship will cause it to vanish.

### Steps to reproduce the issue:
This bug is difficult to reproduce, but it seems to always occur when following the steps to reproduce [this other bug here](https://github.com/tsunamayo/Starship-EVO/issues/1957).

### Environment
- Starship EVO version: 20w19a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
Ghost hinge base; it's not really here, and the base block will disappear when we place something else. You can see it's a ghost because we can place things in it.
![20200503225501_1](https://user-images.githubusercontent.com/33041786/80935189-204e5400-8d91-11ea-9559-6dfebd42058d.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4572693/output_log.txt)

**Comment by captain828** [comment]
Just to clarify from what I've experienced: this isn't a new bug as I've had this happen from 20w18a onwards.

**Comment by tsunamayo** [comment]
Do you confirm you see this only with hinge that were overlapping or not? Because I fixed the overlapping hinge bug.

**Comment by Dwarf-LordPangolin** [comment]
I've seen the ghost blocks for other blocks as well; I'll see if I can get it to duplicate elsewhere.

**Comment by joacmc** [comment]
I also have this issue, when I use symmetry and delete something I get the issue.
I recorded a quick video showing the issue.
[https://youtu.be/gzZCiCN25c8](https://youtu.be/gzZCiCN25c8)

Restarting the game did not solve the issue.

20w21c
Windows 10
GTX 2080 Super

**Comment by tsunamayo** [comment]
I fixed that issue a few build back. Thanks
