### ISSUE TITLE
[New build - DEFAULT] 20w22a: Build Handheld Weapons!

### ISSUE THREAD

**Issue by tsunamayo** [tsunamayo/Starship-EVO#2198]
You can now build handheld weapons!
Simply place the new Handle brick on an Item Stand and start building.
The handle gives a small heat and power boost, but the usual heat / power rules apply.
Link your handle to any weapon to fire it when equipped.
You can build a second handle to get a double handed weapon.
The second handle will activate secondary fire.

Changes and new features:
 - Handheld weapon building feature added
 - Handle brick added
 - Character animation when weapon / multitool equiped updated.
 - Photo Mode [F6] HUD added
 
 Known Issues:
 - Children entity on weapon logic still wip

Bug Fixes:
#2159 Unspawning Entity leave orphaned turret childrens.
#2150 #2151 Incorrect rotate key statement
#2127 #2139 Reloading game after setting a hotkey.
#2140 Incomplete turret link cause issues.
#2137 Issue when controlling an entity built on terrain.
#2126 No locomotion mode air walk.
#2118 #2112 Laser cannot hit target too close.
#2182 Removing children entity can lock the game.

![image](https://user-images.githubusercontent.com/6604318/82849707-0806ca80-9f34-11ea-8607-21a644f8fb07.png)

![image](https://user-images.githubusercontent.com/6604318/82849709-0c32e800-9f34-11ea-88a8-b0adf81621eb.png)

![image](https://user-images.githubusercontent.com/6604318/82849712-0e954200-9f34-11ea-93ae-40932b94b0d2.png)

**Comment by ProPeach** [comment]
This so damn cool! The hands conforming to up to two hands is _awesome!!_

**Comment by tgamorris76** [comment]
Kudo's on new build, is there PvP combat in game? for the hand held weapons?

**Comment by tsunamayo** [comment]
@tgamorris76 no but this should follow-up soon.

**Comment by Aiwii** [comment]
Weapons don't fire...

**Comment by tsunamayo** [comment]
So build is live with the fix! Thanks

**Comment by tsunamayo** [comment]
@Aiwii you need to link a handle to a weapon. I might throw a message if no link is done to help understand!

**Comment by ProPeach** [comment]
Is there anything else you need to do? Discord is trying and no one can get them to fire, we've linked them and given them power etc but nothing so far

**Comment by Aiwii** [comment]
![image](https://user-images.githubusercontent.com/53021785/82851256-79a33200-9ebc-11ea-8b3b-f95eea4759cc.png)
Very nice tsuna

Yes I have linked the handle to the gun

**Comment by Womble-TC** [comment]
how do I get 2 handed weapons? I've built the same gun as yours, but I cant seem to get the other hand to grab the handle. 
![image](https://user-images.githubusercontent.com/29961381/82851335-62356a80-9ef7-11ea-8820-c702eabd1390.png)
not sure what to connect the other handle to

**Comment by ProPeach** [comment]
![image](https://user-images.githubusercontent.com/27857711/82851874-1a174780-9ef9-11ea-9b85-1a5646bcb21b.png)
Not sure if I'm doing something wrong, but I can't remove a secondary handle that I've placed on a gun in the item stand.

**Comment by tsunamayo** [comment]
hum it was working fine for me, I tested it a lot... let me check this out.
@Womble-TC could you send me your blueprint? thanks
Yeah I expected it be quite buggy, thats why I want to give it a bit of time before youtube unveil... Thanks

**Comment by Dwarf-LordPangolin** [comment]
First: these are absolutely amazing!
Second: we've worked out that we can save these with the blueprint system, but how do we pick one up after spawning it with the starter block?

**Comment by ProPeach** [comment]
[Test Gun.zip](https://github.com/tsunamayo/Starship-EVO/files/4679551/Test.Gun.zip)
Here's a gun with two handles
The character only holds one, and only the second handle works as a trigger to fire the gun.
![image](https://user-images.githubusercontent.com/27857711/82854158-86954500-9eff-11ea-8588-c3ff44008aa9.png)

**Comment by tsunamayo** [comment]
@Dwarf yes indeed I will come-up with something. Like a UI for the item stand, also to be able to pick up a weapon when dropped, and also a real drop feature.

**Comment by Aiwii** [comment]
Currently, I can save the item stand but when I load it in while the gun exists somewhere else the model moves I still have two guns tho
![image](https://user-images.githubusercontent.com/53021785/82854417-98f28d00-9ec5-11ea-8d6a-1bb4b0e62c11.png)
One is invis but I can pick up both
![image](https://user-images.githubusercontent.com/53021785/82854445-aa3b9980-9ec5-11ea-806f-190dff85c648.png)

**Comment by tsunamayo** [comment]
@Aiwii yes there seems to be some weirdness with item stand atm, I am investigating issue is not yet clear.

**Comment by tsunamayo** [comment]
I fixed the cannot place the second handle bug.

**Comment by tsunamayo** [comment]
Okay I fixed a bunch of bugs, will do an update soon. Before I would like to know more about the difficulty you have with firing - it works fine on my side!

**Comment by ProPeach** [comment]
It's pretty much the same as before - If you build a gun with one handle and link it to the weapon with power etc, it will not fire when you click primary fire. If you add a second handle to the gun and link it to the same weapon, you can then fire it by clicking secondary fire. Primary fire still does nothing. The character does not hold the second handle either

**Comment by dhelonious** [comment]
Firing weapons does not work for me either. However, if I place and link a second handle to it, primary fire works for me. Though, I cannot get secondary fire to work. Further, I am unable to delete any handle which was once linked to the weapon, because the game considers them all as "the main handle".
Another strange issue occurs in combination with the item stand: If I pick up a weapon by aiming at the item stand (pick item) everything is fine. However, if I try to pick it up by aiming at the weapon itself (grab weapon) then the weapon only appears in the item slot, but the character is not holding it. Instead, the weapon is somewhere in the air. If it put it to an item stand again, the weapon icon still remains in the toolbar and the weapon in the item stand disappears when I scroll through the toolbar. If I drop the weapon icon from the toolbar the entire weapon is deleted, even though it technically was in the item stand.
There are a few more issues with the item stand in combination with weapon handles for me, so I'm not really sure what is going on there.

**Comment by tsunamayo** [comment]
I fixed the primary fire bug for 20w22c.

**Comment by tsunamayo** [comment]
The equip issue is also fixed.

**Comment by dhelonious** [comment]
I can confirm that #2228 fixes all issues I described above!
