### ISSUE TITLE
[Bug] Incorrect texture and z-fighting on small piston

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3164]
Version: 45A

Happens only for small piston, the large one seems to have been spared:
![image](https://user-images.githubusercontent.com/63756057/98157393-33bdb180-1ed1-11eb-9128-e65be8302962.png)

**Comment by Sebateses** [comment]
Have noticed this happening on vents and handles too.

**Comment by tsunamayo** [comment]
Weird... I cant reproduce. Do you get this straight after loading? It might a bug I already fixed. Thx

**Comment by Sebateses** [comment]
@tsunamayo 
I got close to reproducing it but only with the handle. This may be a separate issue i'm not sure.

1. Just loaded the game and spawned in ship. also upon spawning a ghost starter block is hovering above the ship to the side there. Apart from that at this point everything seems fine.

![20201105163750_1](https://user-images.githubusercontent.com/72846347/98202333-e7807900-1f85-11eb-958c-
8cfa1238b108.jpg)

2.Deleted a hinge with child entity attached. Ghost of entity remains.

![20201105163803_1](https://user-images.githubusercontent.com/72846347/98202421-126acd00-1f86-11eb-8da9-b5e1d98e0222.jpg)

3.Placed a random hinge on the wing, nothing happened. Placed a hinge next to that hinge and the deleted ghost entity shifted places and appeared on the second hinge. Same thing seems to happen with pistons.

![20201105163820_1](https://user-images.githubusercontent.com/72846347/98202468-2c0c1480-1f86-11eb-98a2-6a0bd3a34890.jpg)

![20201105163830_1](https://user-images.githubusercontent.com/72846347/98202847-fd426e00-1f86-11eb-9f7d-a75fb470be8e.jpg)

4. This handle is on the other child entity cannon (right side, deleted entity was on the left) which is still apart of the ship and has its texture affected also.

![20201105164837_1](https://user-images.githubusercontent.com/72846347/98203019-5a3e2400-1f87-11eb-927a-6ad10f28ab20.jpg)

5. Reloading the game gets rid of the ghost blocks but the handle still has affected texture.

I hope this helps.

**Comment by Sebateses** [comment]
Ok scratch all that I dont think it has anything to do with hinges/pistons the game just patched into 45B and child enties are deleting properly now.
However the texture on that right side handle is still not right, even on a fresh spawn. It looks damaged and is green as if its repairable when the repair tool is equiped. But does not go back to normal when i try to repair it.
Even if I delete it and replace it, it stays the same. Only on that side though. Really wierd. The other side is fine.
Its not that big of a deal on the handle as its barely noticeable.

**Comment by tsunamayo** [comment]
@Sebateses Is this your ship? Mate our style it is absolutely _fantastique_! I just subbed to the ship so I will test in-game.
I am really digging your style, I cant wait to see what you do with mech, your style would be perfect for that.
I started to use some of your ships in my PR stuff, I hope you dont mind ;)
Cheers

**Comment by tsunamayo** [comment]
So yes I can confirm the weird handle issue. @Kaiser-Indrasil Do you still get that in 20w45b? Thanks

**Comment by Sebateses** [comment]
@tsunamayo thanks alot dude. I would love to do mech but I tried to get a mech going in Space Engineers once. Didnt go so well. I struggled with the whole walking mechanism it kept falling over. All that said i am keen to give it another shot in SEVO.
I am very honored your using my stuff for PR please go right ahead :)

**Comment by tsunamayo** [comment]
@Sebateses nono, do not loose time on that! I had walking mech back in the day but I had to scrap it. I will give a mech core and a few ball-joint piece and I will take care of the animation myself. I have to do a couple physics improvements first.

**Comment by Sebateses** [comment]
@tsunamayo oh nice im very keen to see that in action, cant wait!

**Comment by tsunamayo** [comment]
Okay issue fixed! Thanks
