### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by CusBusAutobus** [tsunamayo/Starship-EVO#3635]
### Short Description of the issue: After i hit play with this character, the game starts to load - it shows a splashscreen after a few seconds the game completely crashes

...

### Steps to reproduce the issue: Open up the game --> Play --> Create new character --> Play with this character

...

### Environment
- Starship EVO version:  21w07a
- Graphics Card:  Radeon RX 570

### Additional information:
player log:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6016889/Player.log)

error log:
[error.log](https://github.com/tsunamayo/Starship-EVO/files/6016894/error.log)

PS I updated my graphical drivers but it didn't help

**Comment by tsunamayo** [comment]
@CusBusAutobus Hi, thanks for reporting this.
Could you please also zip and send me the content of the folder below? 
C:/Users/Jara/AppData/Local/Temp/Moonfire Entertainment/Starship EVO/Crashes
Thanks!

**Comment by CusBusAutobus** [comment]
Hi, sure thing, here you go.

[Crashes.zip](https://github.com/tsunamayo/Starship-EVO/files/6017670/Crashes.zip)

**Comment by CusBusAutobus** [comment]
@tsunamayo Hi man, could you please look at it and tell me what do you think is wrong? I'd really like to play your game since it looks awesome.

Thanks

**Comment by tsunamayo** [comment]
@CusBusAutobus Hi, sorry to have to keep you waiting on this. I have fixed an issue seen in your log but I cant confirm if it was the faulty one. I will push a new update in experimental soon, unfortunately it is quite a big one so it is not ready yet (physics engine overhaul). I keep you posted once it is out (hopefully 1-2 day)!

**Comment by CusBusAutobus** [comment]
@tsunamayo Hi, just wanted to ask how's the update coming up. Thanks.

**Comment by tsunamayo** [comment]
@CusBusAutobus Sorry it took some time, but the build is live in Experimental. Tell me if there any change! Thanks

**Comment by CusBusAutobus** [comment]
@tsunamayo Hi, so I tried the experimental version 21w09a. unfortunately still the same issue :(. I'm sending the new player log and crash dumps below.

[Crashes.zip](https://github.com/tsunamayo/Starship-EVO/files/6096890/Crashes.zip)

**Comment by tsunamayo** [comment]
@CusBusAutobus okay sorry to hear this.
What is your PC config beside the GFX card, and your what is your windows version? Is there anything specific with your config?
1) Also could you desactivate all GFX options (bloom, Ambient Occlusion, vignetting and Chromatic Aberration)
2)Could you try to uninstall the game and reinstall it?

**Comment by CusBusAutobus** [comment]
@tsunamayo Hi, my config is this: 
My windows 10 pro build is this: 18363,1379
cpu ryzen 3 2200g
16GB ddr4 ram
rx 570 4GB VRAM
System along with my steam library are on my ssd
----------------------------------------------------------
I already tried to reinstall the game, it did not help.
I already tried to deactivate all the settings in graphics settings in the game, even tried to change resolution to lower levels and fullscreen to windowed. 

Any help would be appriciated.
Thanks.

**Comment by tsunamayo** [comment]
[Pipe Works.zip](https://github.com/tsunamayo/Starship-EVO/files/6105585/Pipe.Works.zip)
Hi, could you please try to load the character save attached? I want to check if the issue could be related to the space habitat.

**Comment by CusBusAutobus** [comment]
@tsunamayo Hi, yeah so I tried to load the game with the provided save file. The game still crashes, however this time it seemed to crash in a different manner at first.. but after loading it for the second time it crashed in the same way.

Here are new crash dumps:
[Crashes.zip](https://github.com/tsunamayo/Starship-EVO/files/6106334/Crashes.zip)

PS. I know that I'm annoying with this :D

**Comment by tsunamayo** [comment]
@CusBusAutobus no it is not your fault, I would like to know what is wrong with your config, my guess it is GFX related but it is complicated to debug as I dont reproduce the issue at all...

**Comment by CusBusAutobus** [comment]
@tsunamayo  Well that is a bummer. If you think it is gtx related, perhaps I could try to plug in different gpu.. not sure if the card is powerful enough though... Maybe I could also try to use the integrated gpu of ryzen 3 2200g it has vega 8

**Comment by tsunamayo** [comment]
@CusBusAutobus is it a laptop or desktop PC? Yes you can try with the integrated GPU for a start.

**Comment by CusBusAutobus** [comment]
It is a desktop.

Dne st 10. 3. 2021 11:48 uživatel Francois Duret <notifications@github.com>
napsal:

**Comment by CusBusAutobus** [comment]
@tsunamayo It is a desktop... also I just tried launching the gamin using integrated Vega 8 GPU and I the game crashed in the same exact way. Here are error dumps from when I used the integrated GPU.


[Crashes.zip](https://github.com/tsunamayo/Starship-EVO/files/6116663/Crashes.zip)

**Comment by CusBusAutobus** [comment]
@tsunamayo Here you go.. my hardware usage while the game is loading.
![ram](https://user-images.githubusercontent.com/79385042/110960949-8e6b8c00-834f-11eb-8add-d0edc8848705.PNG)

**Comment by CusBusAutobus** [comment]
@tsunamayo Hi any news yet?

**Comment by CusBusAutobus** [comment]
@tsunamayo Still nothing? :(

**Comment by tsunamayo** [comment]
@CusBusAutobus Hi, sorry for the large delay as I am not reproducing those issues are very hard to fix.
I have made progress with the debugging and think it is linked to a camera position error. 
Why it crashes only on your PC is still unknown to me.

Does it crashes immediately after the load screen or after a while?
Did you try the experimental branch? 

I will try a few things once the current update is out.

Thanks

**Comment by CusBusAutobus** [comment]
@tsunamayo  Hi, thank you for not giving up on me :)

As for your questions:
Does it crashes immediately after the load screen or after a while? - Yes it crashes immediately on the splash acreen. When it's loading on the splash screen right at the end I can hear some kind of equipping sound effect and then unity crash handler appears and afterwards the game closes.

Did you try the experimental branch? -Yes, I'm always trying it on the latest version(I have it set on the experimental branch), steam auto-updates the game on startup.

Thank you and have a nice weekend.

**Comment by CusBusAutobus** [comment]
@tsunamayo Hi, just downloaded the latest experimental version and to my absolute suprise **it finally works! :)** Thank you, now this really made my day and I can finally build something. It has been a long wait but sure was worth it.

**Comment by tsunamayo** [comment]
@CusBusAutobus Hi, glad to hear that, you mean the latest experimental or the Voxel Removal preview? Thanks

**Comment by CusBusAutobus** [comment]
@tsunamayo Man honestly I don't know what just happened, at first i thought it was the newest build that fixed it, but it seems like the issue got fixed by itself. I just tried to downgrade to version 21w07 which I'm absolutely positive it didn't work before and now it works... and so does every other version. Before no version worked wheter it was the experimental or the standard. But now suddenly all of them work. 

It honestly is a real mystery to me.

**Comment by CusBusAutobus** [comment]
Perhaps a windows update fixed it? 
![image](https://user-images.githubusercontent.com/79385042/116711858-8afd9400-a9d3-11eb-86e6-ce61ca1ce0fa.png)

I know that i tried on the 10th or 15th of this month.. so it could possibly be one of the updates from the screenshot. Not really sure though.
