### ISSUE TITLE
[New build - EXPERIMENTAL] 23w28a: Planets are finally here!

### ISSUE THREAD

**Issue by tsunamayo** [tsunamayo/Starship-EVO#5117]
Planet have finally landed! 
Fully explorable and procedural planets are replacing the old prefabs.

Dont fall in love with a planet just yet as they will likely be tweaked further which will impact the terrain generation.
Likewise export your ground structures so you can reuse when this happens.

Bugfixes and improvements:
- Player no longer sliding on slope
- Settings might get reset in some conditions

**Comment by tsunamayo** [comment]
The build is up!
So guys I really need you to test the usual stuff, so dont spend too much time on planets yet 😆 .
I just want to make sure there is no hidden game braking regression. If you see something or hear someone from the discord having issues please report here!

I will upload this to default asap.
I have a new trailer and a devlog almost ready to be uploaded.

Cheers

**Comment by Womble-TC** [comment]
WOO! Congrats Tsuna!

**Comment by tsunamayo** [comment]
Also I will do a bigger post once it hits default, there is also tons of stuff not here (like day-night cycle ect).

**Comment by TIKIRobo** [comment]
Currently, i can't even start a new world
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/12022207/output_log.txt)
not sure whats happening exactly, all i do is try to create a new character, hopefully the log helps!

**Comment by tsunamayo** [comment]
Hum how is it going for other people? I can create just fine. @TIKIRobo do you get this all the time?

**Comment by TIKIRobo** [comment]
@tsunamayo yeah, i was able to recreate it 3 times, im reinstalling the game now and trying again

**Comment by TIKIRobo** [comment]
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12022315/Player.log)
another log, even after redownloading the game and unsubscribing from all ws items it still breaks

**Comment by ultrak2k** [comment]
They seem to be decently laggy even on what I'd think is a good computer, but good lord it's pretty (by laggy I just mean like, 30-40 fps on them)
![image](https://github.com/tsunamayo/Starship-EVO/assets/43084360/fc2c27f8-148a-4e73-9a49-39c0ccaca8e4)

**Comment by ultrak2k** [comment]
Also, unsure if this counts as sliding on slopes since this seems quite sleep but I seem to be sliding on this slope

https://github.com/tsunamayo/Starship-EVO/assets/43084360/d6a54e42-f740-46b2-a801-545fab6d2af4

Also, planets seem to be able to spawn with water and life but no atmosphere lol, unsure if that's temporary though
![image](https://github.com/tsunamayo/Starship-EVO/assets/43084360/f665b3d4-984b-4d8a-84dd-70c106469fa2)

**Comment by tsunamayo** [comment]
@ultrak2k What is your config? Can you send your Player.log? Where you moving?

**Comment by tsunamayo** [comment]
@ultrak2k Also what are your normal FPS?

**Comment by ultrak2k** [comment]
> Usually about 100ish in space, and 70+ or so in a ship or the old rings, my GPU (laptop 3060) seems to peak at 100% in general but the FPS drops to about 40-50 on planets

**Comment by ultrak2k** [comment]
> @ultrak2k Also what are your normal FPS?

Usually about 100ish in space, and 70+ or so in a ship or the old rings, my GPU (laptop 3060) seems to peak at 100% in general but the FPS drops to about 40-50 on planets

**Comment by ultrak2k** [comment]
> @ultrak2k What is your config? Can you send your Player.log? Where you moving?
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12022693/Player.log)
I'm on the ringed green world with a surface in the starting system, which si where I experienced slope slip
Unsure what you mean by config, is it the settings.ini file in the same place where player.log is?
[323232.zip](https://github.com/tsunamayo/Starship-EVO/files/12022703/323232.zip)
Here's the savefile

**Comment by ultrak2k** [comment]
> @ultrak2k What is your config? Can you send your Player.log? Where you moving?
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12022693/Player.log)
I'm on the ringed green world with a surface in the starting system, which si where I experienced slope slip
Unsure what you mean by config, is it the settings.ini file in the same place where player.log is?
[323232.zip](https://github.com/tsunamayo/Starship-EVO/files/12022703/323232.zip)
Here's the savefile

**Comment by tsunamayo** [comment]
@ultrak2k Okay lets see what other player are reporting performance wise. I have a 3060 but I have rock solid 60, I will check uncapped how much I get.

**Comment by ultrak2k** [comment]
> @ultrak2k Okay lets see what other player are reporting performance wise. I have a 3060 but I have rock solid 60, I will check uncapped how much I get.

Oh I did hear other people say that their actual desktop GPU 3060s were fine, I think it's just that the laptop one is weaker I realise

**Comment by tsunamayo** [comment]
I have 90 on planet with no clouds, vs 140 in deep space.

**Comment by ultrak2k** [comment]
> I have 90 on planet with no clouds, vs 140 in deep space.

ah, my version of the 3060 is definitely weaker then

**Comment by tsunamayo** [comment]
sorry I have a 3060ti. It should not explain that much though

**Comment by ultrak2k** [comment]
> Also I will do a bigger post once it hits default, there is also tons of stuff not here (like day-night cycle ect).

Does this mean there's a bunch of planet related features not in this build but will be in the default? Or just not specified in this update post

**Comment by tsunamayo** [comment]
yeah nope we will have to wait more for those. I was talking about the post.

**Comment by BeyondStarsLight117** [comment]
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12022867/Player.log)
GPU: AMD Radeon HD 7800 Series
Game Version: 23w28a
Hey Tsuna. i just got the update, and i heard everyone's having a great time despite all the bugs, but for me, whenever i try to load a new world to get in, the game doesnt stop loading. it just stays on the loading screen, silent.

**Comment by tsunamayo** [comment]
@TIKIRobo So I have repushed a build with a few changes related to your error, could you try it out?

**Comment by tsunamayo** [comment]
@BeyondStarsLight117 Hi, could you retry now after the update? Also what bugs? Are they being reported? Thanks

**Comment by Xerma** [comment]
Planets are looking great so far!

![20230711193147_1](https://github.com/tsunamayo/Starship-EVO/assets/32974671/563be19b-942e-4dec-9f5c-e2a9b023a645)

**Comment by tsunamayo** [comment]
![SNAG-0831](https://github.com/tsunamayo/Starship-EVO/assets/6604318/90fb76e4-a933-4264-8569-b52923618b01)

![SNAG-0833](https://github.com/tsunamayo/Starship-EVO/assets/6604318/e2e26eec-db6e-44a7-9619-c129da5d5c02)

**Comment by TIKIRobo** [comment]
@tsunamayo unfortunately it just crashes in a different way with the new update
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12023186/Player.log)

**Comment by tsunamayo** [comment]
@TIKIRobo Could you send me the crash dump? it is located here:
C:/Users/Henry/AppData/Local/Temp/Moonfire Entertainment/Starship EVO/Crashes
Also what is your config? CPU and ram? Thanks

**Comment by TIKIRobo** [comment]
[Crash_2023-07-12_024013170.zip](https://github.com/tsunamayo/Starship-EVO/files/12023365/Crash_2023-07-12_024013170.zip)
@tsunamayo i have an AMD Ryzen 5 2600 6 core, AMD Radeon RX5600 XT and 16GB of ram (sorry i can't remember the specifics of my ram)

**Comment by ItsMeJumpz** [comment]
AMD Ryzen 7 3700X 8-Core Processor, 3593 Mhz, 8 Core(s) , Got the beta experimental branch selected. Crashes when loading new game. No mods installed any longer, and fresh install.

**Comment by tsunamayo** [comment]
@ItsMeJumpz Hi, what is your RAM size?

**Comment by ItsMeJumpz** [comment]
16.0 GB, sorry I forgot that part. 64-bit operating system, x64-based processor

**Comment by tsunamayo** [comment]
Also all what is your OS?

**Comment by TIKIRobo** [comment]
im running windows 10

**Comment by tsunamayo** [comment]
@ItsMeJumpz @BeyondStarsLight117 also please send the new player.log.
This issue is a huge pain, I cant replicate and I have minimum information on what is really bugging. I want to fix that asap but it will need a few back and forth.

**Comment by tsunamayo** [comment]
It seems related to allocating buffers. I need to allocate some large buffer (potentially 1gb large). Could you guys do a CTRL-ALT-DEL and tell me how is your memory usage, before starting the game, and then monitor this while it is loading. Thanks

**Comment by tsunamayo** [comment]
Hi all, I repushed another build with a different approach to the allocation of the faulty buffer (the suspected issue). Tell me how it goes, even if it crashes send me the player.log. Thanks

**Comment by tsunamayo** [comment]
So the issue is that for some reason the game wants to allocate tons of geo right away. After a new world on the tutorial station it should not need to. I suspect it might come from the asteroid generation.
Now that I think of it are you guys all on AMD cards?
Could you start a new world: if it load send a screenshot of F3/Game Performance / Show Engine Data and the player.log?

**Comment by AfterRebelion** [comment]
AMD user here.
Tried 23w28A again, after the patch, and the world now loads, were it didn't before.
However, structures don't render.
<img width="1085" alt="image" src="https://github.com/tsunamayo/Starship-EVO/assets/559819/20c30daa-e23f-483b-a053-b8a61e78ab0a">
And planets either.
<img width="651" alt="image" src="https://github.com/tsunamayo/Starship-EVO/assets/559819/8e024559-a694-4b0e-a715-f51f947e171f">
Only things working correctly are the the sun, the false gas planet, and the ring.

This is with a clean save, just for testing.
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12025568/Player.log)

**Comment by TwoNiner29** [comment]
Hey Tsuna, a couple of funny things I found with planets:

![20230712163208_1](https://github.com/tsunamayo/Starship-EVO/assets/66531332/7846aead-6806-414a-b98d-dda6778f6069)
 
This tree seems to be floating in mid air along the edge of a crater

![20230712163439_1](https://github.com/tsunamayo/Starship-EVO/assets/66531332/6c986e5d-d166-4002-8ba9-d56dfe7a0abb)

some of the planets I've found seem to have too many craters in them, which makes them very uncomfortable to look at for people with trypophobia.

also maybe when approaching planets lightcruise should be a bit faster, it takes a very long time to approach planets

otherwise, everything seems to be working great on my end and the plannets look great so far!

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo Okay, I believe I've gathered enough data to compile a sufficient report.

**Computer specification:**

- CPU: Intel Core i5-12600K 3.7GHz
- GPU: NvIdia GeForce RTX 3070
- RAM: Corsair Vengeance PRO RGB SL DDR4 32GB 3600MHz CL18
- OS: Windows 11 Pro 22H2
- Monitor resolution: 1920x1080 60Hz

**World creation and loading:**

Sanity check passed across the board. I could create a world, load it, and the planets were rendered correctly.
Smoke tests didn't run so great though.

**Game crashes:**

1. First crash occured 5 minutes upon loading the world, when I was mining a monolith by hand.
2. Second crash happened 5 minutes in, when I was roaming the planet on foot.
3. Third crash occured 10 minutes in, when I was soak-testing the game in space beyond the planet's sphere of influence, and then got close to the terrain - the game crashed almost instantenously. Only this crash produced a crash dump - the rest didn't manage to do it, and instead froze indefinitely.
4. Fourth crash occured 25 minutes in, when I was trying my best to crash the game, flying spaceships in lightcruise into the planet's surface, moving in and out of atmosphere, leaving the game to soak in the background for 5 minutes close to the planet's surface, mining, and shooting the ground with ship lasers. The game crashed when I attempted to delete a copied fragment of my Copy-Paste Tool.

All of the crashes mentioned above were experienced during a single Windows session. No computer restarts or sign-outs were involved.

[Crash dump from the 3rd crash](https://github.com/tsunamayo/Starship-EVO/files/12027449/Crash_2023-07-12_091438451.zip)

[Player.log from the 4th crash](https://github.com/tsunamayo/Starship-EVO/files/12027687/Player.log)

[Player-prev.log from the 3rd crash](https://github.com/tsunamayo/Starship-EVO/files/12027691/Player-prev.log)

[World archive from after the tests](https://github.com/tsunamayo/Starship-EVO/files/12027716/23w28a.B.zip)

https://github.com/tsunamayo/Starship-EVO/assets/63756057/87aea3c8-f3b2-4c5e-b679-584dd4f81992

https://github.com/tsunamayo/Starship-EVO/assets/63756057/514dc56c-55cd-43f8-81ea-ccc72e70fcd5


**Performance tests**

Curiously, when the game was left to soak for 10 minutes with the character sitting in space, the game didn't crash as usual, when I roamed the planet.

https://github.com/tsunamayo/Starship-EVO/assets/63756057/e3e3bfa6-9da2-4479-b8d7-324924062479

https://github.com/tsunamayo/Starship-EVO/assets/63756057/e063cf4f-9086-4737-8e15-f746868f32cb


There were some stutters occuring irregularly every few minutes that I couldn't easily correlate with my in-game actions.

https://github.com/tsunamayo/Starship-EVO/assets/63756057/aa3829dc-13e6-4f2e-9cda-79246af21bf1

The game, however, slows down considerably when lots of physics-active entities interact with the planet's surface due to gravity - as in, marbles spawning in from hitting the ground with lasers.
Curiously, the game utilizes the GPU less in such a scenario, as you can see on the graphs to the left.

https://github.com/tsunamayo/Starship-EVO/assets/63756057/5cbd40c3-fc9d-4a28-9fe2-bff8dffc9a61

**Slope sliding**

Not sure if this functionality is implemented yet or not, but on 23w28a (after the hotfixes) it doesn't seem to work.

https://github.com/tsunamayo/Starship-EVO/assets/63756057/dd4b6837-c65d-4c41-a6ca-5226f3bcd5c4

https://github.com/tsunamayo/Starship-EVO/assets/63756057/06fef5bd-ec2a-40c9-9611-e151e3c02481

**Comment by Tisdag1** [comment]
I also have issues when creating a new world with an AMD card. When I create a new world, both the ring around the gas giant & the starting station are invisible. As well as some bugs with some of the other planets.


![20230712085618_1](https://github.com/tsunamayo/Starship-EVO/assets/95005604/de4db51f-fa4e-4ab5-8c04-501b6f6091b6)

![20230712085622_1](https://github.com/tsunamayo/Starship-EVO/assets/95005604/18ea7171-94a6-4dba-b99b-6d50a0470afc)

![20230712085629_1](https://github.com/tsunamayo/Starship-EVO/assets/95005604/31db487a-678a-45bd-80d4-cb5b612531de)

When I exit & reload that same world, everything will load in just fine including the ring & station.

![20230712085800_1](https://github.com/tsunamayo/Starship-EVO/assets/95005604/165e3b06-fea3-4df6-bcb7-387e39c0bd3b)

 However when I go to move, I will hear the sound of me moving while appearing not to move. The only indication that I may actually be moving is the Medical sign on the medical bay moves when I do.

![20230712085809_1](https://github.com/tsunamayo/Starship-EVO/assets/95005604/11d78c61-fb62-48ca-b1e1-98921ba229eb)

![20230712085816_1](https://github.com/tsunamayo/Starship-EVO/assets/95005604/8e0c2ed9-e774-45bf-8adf-1c02cb7f628d)

![20230712085823_1](https://github.com/tsunamayo/Starship-EVO/assets/95005604/2acddef2-5de1-43d2-be83-47949f632348)

I am using AMD Ryzen 7 6800H
Game Version 23w28a
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12029631/Player.log)

**Comment by tsunamayo** [comment]
@Tisdag1 @AfterRebelion @ItsMeJumpz @BeyondStarsLight117 Hi guys, I have just repushed another build with hopefully a fix for AMD cards. Can you test and tell me how it goes? Thanks

**Comment by tsunamayo** [comment]
@TIKIRobo same for you :)

**Comment by tsunamayo** [comment]
@TwoNiner29 Okay good to know, I will try to do something about this. Those are not proper crater but a different step in the generation algo.

**Comment by Tisdag1** [comment]
Nope. Unfortunately the same problems still exist after a fresh start for me.

**Comment by tsunamayo** [comment]
@Tisdag1 Hi, can you send me the player.log and crash dump? Thanks

**Comment by TIKIRobo** [comment]
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12034352/Player.log)
@tsunamayo  there was no crash this time but im still stuck with everything being invisible

**Comment by Tisdag1** [comment]
Sorry, I don't have a crash dump because it doesn't crash for me. But here is my Player log.
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12034357/Player.log)

**Comment by tsunamayo** [comment]
@AfterRebelion @ItsMeJumpz @BeyondStarsLight117 @TIKIRobo @Tisdag1 So I have created a new branch, called planets_amd, instead of experimental. Could you try this branch and tell me how it goes? I removed several feature in the generation, I want to see if it still have issues.
Thanks

**Comment by Tisdag1** [comment]
@tsunamayo Okay, so I started a new game with the Planets_amd branch & still no luck. I don't know if it helps, but I have noticed that even though It doesn't look like I am moving apparently I am. I have noticed that after trying to move around, when I exit & relaunch the game, I load in at the new updated location that I must have been at when I exited.

**Comment by tsunamayo** [comment]
It might be coming from the asteroid, let me repush something.

**Comment by tsunamayo** [comment]
@Tisdag1 @TIKIRobo I have repushed something without the asteroids. Tell me how it goes. I am really sorry it will take again some time to figure out, it is a bit laborious but we will sort it out. We already made big progress.

**Comment by tsunamayo** [comment]
@ultrak2k So I have fixed the slope. No yet pushed though.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Thanks for the detailed report. There is some info on the third crash, it crashed because of a malloc for the rigidbody, which is surprising. Did you overclocked your RAM? thanks

**Comment by TIKIRobo** [comment]
@tsunamayo still in the void unfortunately :(
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12035097/Player.log)

**Comment by Tisdag1** [comment]
@tsunamayo Sadly that didn't work. I even tried with a fresh install & the issues still persist.
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12035192/Player.log)

**Comment by Kaiser-Indrasil** [comment]
> @Kaiser-Indrasil Thanks for the detailed report. There is some info on the third crash, it crashed because of a malloc for the rigidbody, which is surprising. Did you overclocked your RAM? thanks

Actually yeah, up to 3600MHz just with automatic XMP, no manual tinkering whatsoever.

**Comment by ultrak2k** [comment]
> Planet have finally landed! Fully explorable and procedural planets are replacing the old prefabs.
> 
> Dont fall in love with a planet just yet as they will likely be tweaked further which will impact the terrain generation. Likewise export your ground structures so you can reuse when this happens.
> 
> The scale of the solar system has been tweaked a bit.
> 
> Bugfixes and improvements:
> 
>     * Player no longer sliding on slope
> 
>     * Settings might get reset in some conditions
> 
> 
> ![SNAG-0845](https://user-images.githubusercontent.com/6604318/252814609-e9928b20-3d29-4135-bc4d-9eab4349189f.png)

Out of curiosity, what tweaks to the terrain gen are you imagining?

**Comment by AfterRebelion** [comment]
Just tested the `planet_amd` branch, and same result, rendering is funky.
<img width="411" alt="image" src="https://github.com/tsunamayo/Starship-EVO/assets/559819/1bd032ae-6f0c-47d0-b46e-bfb46c2ba67a">

> I also have issues when creating a new world with an AMD card. When I create a new world, both the ring around the gas giant & the starting station are invisible. As well as some bugs with some of the other planets.
> **When I exit & reload that same world, everything will load in just fine** including the ring & station.
> I am using AMD Ryzen 7 6800H Game Version 23w28a [Player.log](https://github.com/tsunamayo/Starship-EVO/files/12029631/Player.log)

Tried this, to exit and reload a world, and it spawned me inside the sun, just in the middle of it. The torus was also there.
It also changed my game resolution to something weird, in the 4:3 ratio.
Apart from that, the same rendering issues as before.
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12038090/Player.log)

**Comment by BigBadKangaroo** [comment]
> @AfterRebelion @ItsMeJumpz @BeyondStarsLight117 @TIKIRobo @Tisdag1 So I have created a new branch, called planets_amd, instead of experimental. Could you try this branch and tell me how it goes? I removed several feature in the generation, I want to see if it still have issues. Thanks

Hi there,

I tested the AMD branch and many performace / rendering issues have gone. It's much more stable even when zipping around the solar system with super high movement speed. Planets are rendering in much more smoothly.

**Comment by tsunamayo** [comment]
> > @Kaiser-Indrasil Thanks for the detailed report. There is some info on the third crash, it crashed because of a malloc for the rigidbody, which is surprising. Did you overclocked your RAM? thanks
> 
> Actually yeah, up to 3600MHz just with automatic XMP, no manual tinkering whatsoever.

Because some other people reported a similar issue, it was linked to OC memory. It is something memory related, it is not from my code (it cant allocate memory, and I doubt it was just a space issue)

**Comment by tsunamayo** [comment]
@AfterRebelion @Tisdag1 @TIKIRobo  @ItsMeJumpz @BeyondStarsLight117 the AMD fix is up, now on experimental. Thanks

**Comment by Kaiser-Indrasil** [comment]
> > > @Kaiser-Indrasil Thanks for the detailed report. There is some info on the third crash, it crashed because of a malloc for the rigidbody, which is surprising. Did you overclocked your RAM? thanks
> > 
> > 
> > Actually yeah, up to 3600MHz just with automatic XMP, no manual tinkering whatsoever.
> 
> Because some other people reported a similar issue, it was linked to OC memory. It is something memory related, it is not from my code (it cant allocate memory, and I doubt it was just a space issue)

I was playing for 2 hours straight lately and didn't manage to crash the game with OC RAM enabled. I will continue to monitor.

**Comment by Dwarf-LordPangolin** [comment]
Hi Tsuna! Just wanted to swing by to say that the planets are _amazing_. These are some of the best procedurally generated planets I've ever seen in a game. Beyond that though, you've also succeeded in giving them a lot of personality; they're not just pretty, they feel immersive and intriguing. I am so stoked about playing on them when survival is ready. This game just continues to go impress and go beyond my expectations.
